# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc",".rbenv-version","Rakefile","Gemfile","Gemfile.lock","changelog.md","README.md",'sass','watch.sh','node_modules'] # files to exclude
paginate: 1
pygment: true
production: true
env : production

# Configuration
title: Activités Saint-Nicaise
tagline: Groupe de loisirs créatifs
author:
  name: Activité Saint-Nicaise
  email: activitessaintnicaise@gmail.com
  github: activitessaintnicaise
  twitter: activitesaintnicaise
  feedburner: activitessaintnicaise
production_url: http://activitesaintnicaise.org

# Google analyitcs API
gadash :
  api_key : AIzaSyDbLyMADJ40iXp4JpRSRrsgAWFozSLoMvA
  client_id : 
    developement : 873987230620-73jsn9tivn0kepstu8jtl1cdjpt5avv3.apps.googleusercontent.com
    production : 873987230620-22r92a7bf0jelikj0p09ptkc1pi3qst2.apps.googleusercontent.com
  table_id : ga:67617751

prose:
  siteurl: "http://activitesaintnicaise.org"
  relativeLinks: ''
  media: 'media'
  ignore:
    - CNAME
    - robots.txt
    - sitemap.txt
    - atom.xml
    - _config.yml
    - index.html
    - board.html
    - gallery.html
    - actualites.html
    - changelog.md
    - 404.html
    - .gitignore
    - .gitmodules
    - .htaccess
    - Gemfile
    - favicon.ico
    - gruntfile.js
    - package.json
    - npm-debug.log
    - Rakefile
    - slide-cannage.html
    - slide-patchwork.html
    - slide-refection-fauteuil.html
    - slide-restauration-tableaux.html
    - slide-tapisserie-aiguille.html
    - stages.html
    - /_layouts
    - /_includes
    - /_plugins
    - /_site
    - /_rake
    - /assets
    - /galerie
    - /images
    - /phantomas
    - /node_modules
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Ajouter un title"
          placeholder: "titre de la page"


# Jekyll bootstrap configuration
JB:
  version: 0.2.13
  BASE_PATH: false
  ASSET_PATH: false
  archive_path: /actualites.html
  comments:
    provider: false
    disqus:
      short_name: 
    livefyre:
      site_id: 
    intensedebate:
      account: 123abc
    facebook:
      appid: 
      num_posts: 
      width: 
      colorscheme: light
  analytics:
    provider: google
    google:
      tracking_id: UA-37417229-1
    getclicky:
      site_id: 
    mixpanel:
      token: _MIXPANEL_TOKEN_
  pingdom : 51764493e6e53dd01f000000
  sharing:
    provider: false
