backend:
  name: github
  repo: activitessaintnicaise/activitessaintnicaise.github.com # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "assets/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "stages" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Stages" # Used in the UI, ie.: "New Post"
    folder: "_posts/stages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titre", name: "title", widget: "string", tagname: "titre"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
    meta:
      - {label: "Categorie", name: "category", widget: "string"}
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Billet" # Used in the UI, ie.: "New Post"
    folder: "_posts/actualites"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Contenu", name: "body", widget: "markdown"}
    meta:
      - {label: "Categorie", name: "category", widget: "string"}