backend:
  name: github
  repo: activitessaintnicaise/activitessaintnicaise.github.com # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "assets/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "stages" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Stages" # Used in the UI, ie.: "New Post"
    folder: "_posts/stages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Publié", name: "published", widget: "boolean"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Période", name: "periode", widget: "string"}
      - {label: "Lieu", name: "lieu", widget: "string", default: "Maison Saint-Nicaise - Rouen"}
      - {label: "Contact", name: "contact", widget: "string", default: "Vanessa Laplanche"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Categorie", name: "category", widget: "hidden", default: "stages"}
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Actualités" # Used in the UI, ie.: "New Post"
    folder: "_posts/actualites"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publié", name: "published", widget: "boolean", default: true}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Categorie", name: "category", widget: "hidden", default: "actualites"}
  - name: "activity" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Activités" # Used in the UI, ie.: "New Post"
    folder: "_activities"
    #slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publié", name: "published", widget: "boolean", default: true}
      - {label: "Contenu", name: "body", widget: "markdown"}
  - name: "images" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Images" # Used in the UI, ie.: "New Post"
    folder: "_realisations"
    #slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publié", name: "published", widget: "boolean", default: true}
      - {label: "Contenu", name: "image", widget: "image"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Cours", name: "select", widget: "select", options: ["Fauteuil", "Tableaux", "Patchwork"]}
      - name: authors
        label: Authors
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Description, name: description, widget: markdown}
      - name: Activité
        label: Activité
        widget: relation
        collection: activities
        searchFields: [title]
        valueField: title

  - name: "settings"
    label: "Configuration"
    editor:
      preview: false
    files:
      - name: "Dates"
        label: "Dates"
        file: "_data/dates.yml"
        description: "Date de reprises"
        fields:
          - {label: "Date fauteuil", name: "date_fauteuil", widget: "string", required: false}
          - {label: "Date patchwork", name: "date_patchwork", widget: "string", required: false}
          - {label: "Date cannage", name: "date_cannage", widget: "string", required: false}
          - {label: "Date tableau", name: "date_tableau", widget: "string", required: false}
      - name: "Informations"
        label: "Informations"
        file: "_data/informations.yml"
        description: "Informations générales"
        fields:
          - {label: "Référent pour contact", name: "referent", widget: "string", required: false}
          - {label: "Numéro de téléphone", name: "telephone", widget: "string", required: false}
          - {label: "Adresse courriel", name: "email", widget: "string", required: false}
      - name: "Prix"
        label: "Prix"
        file: "_data/prix.yml"
        description: "Cotisations à l'association'"
        fields:
          - {label: "Prix adhésion", name: "prix_adhesion", widget: "string", required: false}
          - {label: "Prix fauteuil", name: "prix_fauteuil", widget: "string", required: false}
          - {label: "Prix patchwork", name: "prix_patchwork", widget: "string", required: false}
          - {label: "Prix cannage", name: "prix_cannage", widget: "string", required: false}
          - {label: "Prix tableau", name: "prix_tableau", widget: "string", required: false}
          - {label: "Prix salle fauteuil", name: "prix_salle_fauteuil", widget: "string", required: false}
          - {label: "Prix salle patchwork", name: "prix_salle_patchwork", widget: "string", required: false}
          - {label: "Prix salle cannage", name: "prix_salle_cannage", widget: "string", required: false}
          - {label: "Prix salle tableau", name: "prix_salle_tableau", widget: "string", required: false}
